# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{orangewire_sender}
  s.version = "1.0.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Joshua Davison"]
  s.date = %q{2010-05-02}
  s.description = %q{Sends messages to The Orangewire}
  s.email = %q{josh@stringbot.com}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.rdoc"
  ]
  s.files = [
    ".document",
     ".gitignore",
     "LICENSE",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "lib/orangewire/errors.rb",
     "lib/orangewire_sender.rb",
     "orangewire_sender.gemspec",
     "test/test_orangewire_sender.rb",
     "test/teststrap.rb"
  ]
  s.homepage = %q{http://github.com/stringbot/orangewire_sender}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.6}
  s.summary = %q{Sends messages to The Orangewire}
  s.test_files = [
    "test/test_orangewire_sender.rb",
     "test/teststrap.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<rest-client>, [">= 0"])
      s.add_development_dependency(%q<riot>, [">= 0.10.13"])
      s.add_development_dependency(%q<rr>, [">= 0.10.10"])
    else
      s.add_dependency(%q<rest-client>, [">= 0"])
      s.add_dependency(%q<riot>, [">= 0.10.13"])
      s.add_dependency(%q<rr>, [">= 0.10.10"])
    end
  else
    s.add_dependency(%q<rest-client>, [">= 0"])
    s.add_dependency(%q<riot>, [">= 0.10.13"])
    s.add_dependency(%q<rr>, [">= 0.10.10"])
  end
end

